name: datesync
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_ui_auth: ^3.0.1
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_database: ^12.0.4
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^2.0.1
  syncfusion_flutter_calendar: ^31.2.12
  sqflite: ^2.4.2
  path: ^1.9.1
  curved_navigation_bar: ^1.0.6
  flutter_launcher_icons: ^0.14.4
  fl_chart: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/img/icon.png"
flutter:
  uses-material-design: true

  assets:
    - lib/assets/img/
